# Generated by Django 3.0 on 2019-12-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sluglineuser",
            name="writer_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
