# Generated by Django 3.0.2 on 2020-03-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_sluglineuser_writer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sluglineuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
