# Generated by Django 2.2.7 on 2019-12-11 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('is_article_of_issue', models.BooleanField()),
                ('is_promo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(null=True)),
                ('volume_num', models.IntegerField()),
                ('issue_num', models.IntegerField()),
                ('pdf', models.FileField(null=True, upload_to='issue_pdfs/')),
            ],
            options={
                'ordering': ['-volume_num', '-issue_num'],
            },
        ),
        migrations.CreateModel(
            name='WordpressArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Article')),
                ('content_html', models.TextField()),
            ],
            bases=('content.article',),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Issue'),
        ),
    ]
