# Generated by Django 2.2.7 on 2019-12-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-volume_num', '-issue_num']},
        ),
        migrations.AddField(
            model_name='issue',
            name='pdf',
            field=models.FileField(null=True, upload_to='issue_pdfs/'),
        ),
    ]
