# Generated by Django 2.2.7 on 2019-12-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_wordpress",
            field=models.BooleanField(default=False),
        ),
    ]
