# Generated by Django 2.2.7 on 2019-12-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20191211_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpressarticle',
            name='is_promo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
