# Generated by Django 2.2.7 on 2019-12-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_wordpressarticle_is_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpressarticle',
            name='is_article_of_issue',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
