# Generated by Django 3.0.2 on 2020-03-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_wordpress',
        ),
        migrations.AddField(
            model_name='article',
            name='content_slate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_wordpress',
            field=models.TextField(null=True),
        ),
    ]
