# Generated by Django 3.0.2 on 2020-03-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200319_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_slate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_wordpress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
