# Generated by Django 3.0.4 on 2020-05-05 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_auto_20200329_2013"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="issue", unique_together={("volume_num", "issue_num")},
        ),
    ]
