# Generated by Django 3.0.2 on 2020-03-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200322_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_slate',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_wordpress',
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('SLATE', 'Slate'), ('WORDPRESS', 'Wordpress')], default='WORDPRESS', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content_raw',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
