# Generated by Django 3.0.4 on 2020-05-06 19:08

from django.db import migrations


def convert_issue_numbers(apps, schema_editor):
    Issue = apps.get_model("content", "Issue")
    for issue in Issue.objects.all():
        issue.issue_code = str(issue.issue_num)
        issue.save()


def convert_issue_numbers_reverse(apps, schema_editor):
    Issue = apps.get_model("content", "Issue")
    for issue in Issue.objects.all():
        issue.issue_code = ""
        issue.save()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_issue_issue_code"),
    ]

    operations = [
        migrations.RunPython(
            convert_issue_numbers, reverse_code=convert_issue_numbers_reverse
        )
    ]
