# Generated by Django 3.0.4 on 2020-05-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20200506_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-volume_num', '-issue_code']},
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('volume_num', 'issue_code')},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_num',
        ),
    ]
