# Generated by Django 3.0.6 on 2020-05-07 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_auto_20200506_1516"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(1970, 1, 1, 0, 0)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("in-progress", "In Progress"),
                    ("okayed", "Okayed"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
