# Generated by Django 3.0.6 on 2020-09-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_auto_20200507_1543"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="issue_pdfs/"),
        ),
    ]
