# Generated by Django 3.0.6 on 2020-09-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_auto_20200908_0414"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="colour",
            field=models.CharField(
                choices=[
                    ("blastoff-blue", "Blastoff Blue"),
                    ("celestial-blue", "Celestial Blue"),
                    ("cosmic-orange", "Cosmic Orange"),
                    ("fireball-fuchsia", "Fireball Fuchsia"),
                    ("galaxy-gold", "Galaxy Gold"),
                    ("gamma-green", "Gamma Green"),
                    ("gravity-grape", "Gravity Grape"),
                    ("liftoff-lemon", "Liftoff Lemon"),
                    ("lunar-blue", "Lunar Blue"),
                    ("martian-green", "Martian Green"),
                    ("orbit-orange", "Orbit Orange"),
                    ("outrageous-orchid", "Outrageous Orchid"),
                    ("planetary-purple", "Planetary Purple"),
                    ("pulsar-pink", "Pulsar Pink"),
                    ("reentry-red", "Reentry Red"),
                    ("rocket-red", "Rocket Red"),
                    ("sunburst-yellow", "Sunburst Yellow"),
                    ("terra-green", "Terra Green"),
                    ("terrestrial-teal", "Terrestial Teal"),
                    ("venus-violet", "Venus Violet"),
                    ("pastel-blue", "Pastel Blue"),
                    ("pastel-buff", "Pastel Buff"),
                    ("pastel-canary", "Pastel Canary"),
                    ("pastel-goldenrod", "Pastel Goldenrod"),
                    ("pastel-grey", "Pastel Grey"),
                    ("pastel-green", "Pastel Green"),
                    ("pastel-orchid", "Pastel Orchid"),
                    ("pastel-pink", "Pastel Pink"),
                    ("pastel-salmon", "Pastel Salmon"),
                    ("paper", "Paper"),
                ],
                default="paper",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="issue", name="description", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
