# Generated by Django 3.0.6 on 2020-09-15 02:18

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_auto_20200908_1918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=content.models.OverwriteStorage(),
                upload_to="issue_pdfs",
            ),
        ),
    ]
