name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate schema
      run: python manage.py generate_swagger schema.yml

    - name: Create webpage
      run: |
        mkdir public
        npx redoc-cli bundle swagger.yml
        mv redoc-static.html public/index.html

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.1.0
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
